=== paulmai193/socket-io/src/main/resource/datapackage.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	elementFormDefault="qualified" attributeFormDefault="unqualified">
	<!-- XML Schema Generated from XML Document on Wed Nov 12 2014 08:43:46 
		GMT+0700 (SE Asia Standard Time) -->
	<!-- with XmlGrid.net Free Online Service http://xmlgrid.net -->
	<xs:element name="datapackage">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="define">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="define-command" maxOccurs="unbounded"
								minOccurs="1">
								<xs:complexType>
									<xs:simpleContent>
										<xs:extension base="xs:string">
											<xs:attribute name="name" type="xs:string" use="required"></xs:attribute>
											<xs:attribute name="value" type="xs:string" use="required"></xs:attribute>
											<xs:attribute name="type" type="xs:string" use="required"></xs:attribute>
										</xs:extension>
									</xs:simpleContent>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute name="type" type="xs:string" use="required"></xs:attribute>
					</xs:complexType>
				</xs:element>
				<xs:element name="command" maxOccurs="unbounded"
					minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="data" minOccurs="0" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="element" minOccurs="0" maxOccurs="unbounded">
											<xs:complexType>
												<xs:attribute name="name" type="xs:string" use="required"></xs:attribute>
												<xs:attribute name="type" type="xs:string" use="required"></xs:attribute>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
									<xs:attribute name="name" type="xs:string" use="required"></xs:attribute>
									<xs:attribute name="type" type="xs:string" use="required"></xs:attribute>
									<xs:attribute name="breakvalue" type="xs:string"
										use="optional"></xs:attribute>
									<xs:attribute name="continuevalue" type="xs:string"
										use="optional" default="n/a"></xs:attribute>
									<xs:attribute name="elementtype" type="xs:string"
										use="optional"></xs:attribute>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute name="value" type="xs:int"></xs:attribute>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== paulmai193/socket-io/src/implement/define/ServerDataPackage.xml
<?xml version="1.0"?>
<datapackage xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="jar:file:/e:/FoodMob/Android/workspace/Test/src/lib/socketio.jar!/logia/io/define/datapackage.xsd">
	<define>
		<define-command name="ping" value="0">server.datapackage.PongData</define-command>
		<define-command name="ping" value="1">server.datapackage.PingData</define-command>
		<define-command name="receive_message" value="2">server.datapackage.MessageData</define-command>
		<define-command name="send_message" value="3">server.datapackage.MessageData
		</define-command>
		<define-command name="contact" value="4">server.datapackage.ContactData
		</define-command>
		<define-command name="file" value="5">server.datapackage.FileData
		</define-command>
		<define-command name="disconnect" value="6">server.datapackage.DisconnectData
		</define-command>
		<define-command name="listnumber" value="7">server.datapackage.ListNumberData
		</define-command>
		<define-command name="ping" value="1001">server.datapackage.TestData</define-command>
	</define>

	<command value="0"></command>

	<command value="1"></command>

	<command value="2">
		<data name="user" type="int" />
		<data name="message" type="String" />
	</command>

	<command value="3">
		<data name="user" type="int"></data>
		<data name="message" type="String"></data>
	</command>

	<command value="4">
		<data name="contacts" type="List" elementtype="server.datapackage.Contact">
			<element name="name" type="String"></element>
			<element name="phone" type="String"></element>
			<element name="email" type="String"></element>
		</data>
	</command>

	<command value="5">
		<data name="file" type="bytearray"></data>
	</command>

	<command value="6">
	</command>

	<command value="7">
		<data name="listnumber" type="list" elementtype="double">
			<element name="number" type="double"></element>
		</data>
	</command>

	<command value="1001">
		<data name="number" type="long" checkvalue="0"></data>
		<data name="name" type="string"></data>
		<data name="message" type="string"></data>
	</command>

</datapackage>

=== paulmai193/socket-io/src/test/java/implement/define/ServerDataPackage.xml
<?xml version="1.0"?>
<datapackage xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="datapackage.xsd">
	<define type="int">
		<define-command name="ping" value="0">implement.server.datapackage.PongData</define-command>
		<define-command name="ping" value="1">implement.server.datapackage.PingData</define-command>
		<define-command name="receive_message" value="2">implement.server.datapackage.MessageData</define-command>
		<define-command name="send_message" value="3">implement.server.datapackage.MessageData</define-command>
		<define-command name="contact" value="4" type="receive">implement.server.datapackage.ContactData</define-command>
		<define-command name="file" value="5">implement.server.datapackage.FileData</define-command>
		<define-command name="disconnect" value="6">implement.server.datapackage.DisconnectData</define-command>
		<define-command name="listnumber" value="7" type="send">implement.server.datapackage.ListNumberData</define-command>
		<define-command name="test" value="10">implement.server.datapackage.TestData</define-command>
		<define-command name="result" value="11">implement.server.datapackage.ResultData</define-command>
		<define-command name="json" value="12">implement.server.datapackage.JsonData</define-command>
	</define>

	<command value="0"></command>

	<command value="1"></command>

	<command value="2">
		<data name="user" type="int" />
		<data name="message" type="String" />
	</command>

	<command value="3">
		<data name="user" type="int"></data>
		<data name="message" type="String"></data>
	</command>

	<command value="4">
		<data name="contacts" type="List" elementtype="server.datapackage.Contact">
			<element name="name" type="String"></element>
			<element name="phone" type="String"></element>
			<element name="email" type="String"></element>
		</data>
	</command>

	<command value="5">
		<data name="file" type="file"></data>
	</command>

	<command value="6">
	</command>

	<command value="7">
		<data name="listnumber" type="list" elementtype="double">
			<element name="number" type="double"></element>
		</data>
	</command>

	<command value="10">
		<data name="number" type="long" breakvalue="0"></data>
		<data name="name" type="string"></data>
		<data name="message" type="string"></data>
	</command>
	
	<command value="12">
		<data name="jsonelement" type="jsonobject"></data>
	</command>

</datapackage>

=== paulmai193/socket-io/target/test-classes/implement/define/ClientDataPackage.xml
<?xml version="1.0" encoding="UTF-8"?>
<datapackage xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="datapackage.xsd">
	<define type="int">
		<define-command name="pong" value="0">implement.client.datapackage.PongData</define-command>
		<define-command name="ping" value="1">implement.client.datapackage.PingData</define-command>
		<define-command name="receive_message" value="2">implement.client.datapackage.MessageData</define-command>
		<define-command name="send_message" value="3">implement.client.datapackage.MessageData</define-command>
		<define-command name="contact" value="4">implement.client.datapackage.ContactData</define-command>
		<define-command name="file" value="5">implement.client.datapackage.FileData</define-command>
		<define-command name="disconnect" value="6">implement.client.datapackage.DisconnectData</define-command>
		<define-command name="listnumber" value="7">implement.client.datapackage.ListNumberData</define-command>
		<define-command name="test" value="10">implement.client.datapackage.TestData</define-command>
		<define-command name="result" value="11">implement.client.datapackage.ResultData</define-command>
	</define>

	<command value="0"></command>

	<command value="1"></command>

	<command value="2">
		<data name="user" type="int"></data>
		<data name="message" type="String"></data>
	</command>

	<command value="3">
		<data name="user" type="int"></data>
		<data name="message" type="String"></data>
	</command>

	<command value="4">
		<data name="contacts" type="List" elementtype="client.datapackage.Contact">
			<element name="name" type="String"></element>
			<element name="phone" type="String"></element>
			<element name="email" type="String"></element>
		</data>
	</command>

	<command value="5">
		<data name="file" type="file"></data>
	</command>

	<command value="6">
	</command>

	<command value="7">
		<data name="listnumber" type="list" elementtype="double">
			<element name="number" type="double"></element>
		</data>
	</command>

	<command value="10">
		<data name="number" type="long" breakvalue="0"></data>
		<data name="name" type="string"></data>
		<data name="message" type="string"></data>
	</command>

</datapackage>

=== paulmai193/socket-io/src/test/java/implement/define/ClientDataPackage.xml
<?xml version="1.0" encoding="UTF-8"?>
<datapackage xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="jar:file:/C:\Users\Paul Mai\.m2\repository\logia\logia-socketio\0.0.2\logia-socketio-0.0.2-sources.jar!/logia/io/define/datapackage.xsd">
	<define>
		<define-command name="pong" value="0">client.datapackage.PongData</define-command>
		<define-command name="ping" value="1">client.datapackage.PingData</define-command>
		<define-command name="receive_message" value="2">client.datapackage.MessageData</define-command>
		<define-command name="send_message" value="3">client.datapackage.MessageData</define-command>
		<define-command name="contact" value="4">client.datapackage.ContactData</define-command>
		<define-command name="file" value="5">client.datapackage.FileData</define-command>
		<define-command name="disconnect" value="6">client.datapackage.DisconnectData</define-command>
		<define-command name="listnumber" value="7">client.datapackage.ListNumberData</define-command>
		<define-command name="ping" value="1001">client.datapackage.TestData</define-command>
	</define>

	<command value="0"></command>

	<command value="1"></command>

	<command value="2">
		<data name="user" type="int"></data>
		<data name="message" type="String"></data>
	</command>

	<command value="3">
		<data name="user" type="int"></data>
		<data name="message" type="String"></data>
	</command>

	<command value="4">
		<data name="contacts" type="List" elementtype="client.datapackage.Contact">
			<element name="name" type="String"></element>
			<element name="phone" type="String"></element>
			<element name="email" type="String"></element>
		</data>
	</command>

	<command value="5">
		<data name="file" type="bytearray"></data>
	</command>

	<command value="6">
	</command>

	<command value="7">
		<data name="listnumber" type="list" elementtype="double">
			<element name="number" type="double"></element>
		</data>
	</command>

	<command value="1001">
		<data name="number" type="long" breakvalue="0"></data>
		<data name="name" type="string"></data>
		<data name="message" type="string"></data>
	</command>

</datapackage>
